### ISSUE TITLE
Archive repo offline

### ISSUE THREAD

**Issue by ghost** [databrary/iteratees#1]

**Comment by ghost** [comment]
https://mvnrepository.com/artifact/org.databrary/iteratees_2.11/0.1

**Comment by ghost** [comment]
@dylex How do you feel about transferring this repo under your name instead of databrary? I am just trying to reduce the amount of repos, so that people don't overlook the active ones.

**Comment by dylex** [comment]
"Isn't that what pinned repositories are for?" But seriously, if NYU is willing to relinquish their copyright on this to me, I can certainly take it.

**Comment by ghost** [comment]
Good point... I will try pinned for now. I don't think anybody has any hesitation about relinquishing copyright, but no need to exercise that yet.
